### ISSUE TITLE
makeAP for DJI Air 2S (dji32) returns NA altitudes in lichti

### ISSUE THREAD

**Issue by Runge123** [gisma/uavRmp#11]
Design a plan in QGC for DJI Air 2S (survey mode, agl, corresponding camera parameters, etc.) and export the generated ".plan" file to uavRmp. I set up the makeAP call very similar to the example on https://gisma.github.io/uavRmp/articles/uavRmp_1.html#field-guide. 

When loading the csv (generated in uavRmp) to lichti I get NA in all WP, i.e. I have no flight altitude values in agl mode. FYI I installed uavRmp again from the github.  Here an example of the makeAP call

uavRmp::makeAP(surveyArea=fp,
                             useMP = TRUE,
                             projectDir = "E:/path",
                             followSurface = TRUE,
                             demFn = dsm,
                             horizonFilter = 3,
                             followSurfaceRes = 3,
                             altFilter = 2.5,
                             cameraType = "dji32",
                             uavType = "dji_csv", 
                             above_ground = FALSE)

This code was working just a few hours ago with cameraType = dji4k . I'm trying to find the root cause of the error but I can't find the solution, thanks :)

**Comment by gisma** [comment]
Hi @Runge123 I need the DSM and the plan file to figure out what happend

**Comment by Runge123** [comment]
Hi @gisma, in the link you will find the requested files 

https://drive.google.com/drive/folders/1Ij-Hs8nXiVEUbLrlwx7623JbRLeJ39Z0?usp=share_link

Thanks:)

**Comment by gisma** [comment]
Yup the last update generates an error . However NA is weird
Thanks for the files

**Comment by gisma** [comment]
@Runge123 pls re-install and  try again

**Comment by Runge123** [comment]
I reinstalled uavRmp from github and on the first try I was able to create the output CSV, uploaded it to lichti and received NA in the WP's again.

So I tried again in case I made a mistake and I received an error related to fDF.  
```
Error in names(fDF) <- nms : 
  'names' attribute [50] must be the same length as the vector [49].
```

**Comment by gisma** [comment]
please install again. probably you were a second to fast

**Comment by Runge123** [comment]
Now I got elevation values for each WP, thanks for the prompt solution :)
The hawk is looking forward to take off!

**Comment by gisma** [comment]
fine.
