### ISSUE TITLE
UgCS

### ISSUE THREAD

**Issue by adobrovolskiy-ugcs** [gisma/uavRmp#4]
Hi, guys
what do you mean here - "Other commmerical competitors like the powerful ugcs software package are still lacking an advanced capability for generating smooth and save surface following flight tasks for low AGL (above ground level) altitudes."
I'm CTO of SPH Engineering and I think that I know functionality of UgCS...

**Comment by gisma** [comment]
Hi @adobrovolskiy-ugcs,

Sorry for the delay. 
I hope that you know... 

I have never intended to evaluate UgCS negatively. The Pro version, which you have kindle made available to us as an educational license, of course has the possibility to use your own DEM for planning.

As far as I have used it correctly, the AGL heights were calculated on the basis of the terrain model along the planned flight path with the resolution of the footprints. This somehow arbitrary height values sampling will result in some crucial problems. Assuming I fly 15 meters in a heavily carved terrain above a forest with irregular clearings and an average tree height of about 30 meters, I will land sooner or later in the trees. I need a kind of an smoothed flight path that is able to deal with the surface altitude differences according to the spatial scale of  the surface structures (clearings, woods, valleys ridges).

Maybe this kind of interpolation was/is already implemented. As far as I know last fall it was not yet the case. 

However I will adapt this  sentence referring to UgCS or delete the reference to your software if you want

best  Chris

**Comment by adobrovolskiy-ugcs** [comment]
Hi Chris, thank you for answer. UgCS out of the box uses SRTM and other free sources of elevation data. Sometimes they are not precise and of course will not allow to fly safely on 15m AGL over rugged terrain or over forest. 
But UgCS Pro or UgCS Enterprise can import your custom DEM data. If you have DSM (surface model with trees, obstacles etc) UgCS should plan mission accordingly.
