### ISSUE TITLE
warning caused by new sf version

### ISSUE THREAD

**Issue by edzer** [gisma/uavRmp#6]
With sf 0.7-0 (submitted to CRAN) I now see
```r
> library(uavRmp)
Warning message:
replacing previous import ‘gdalUtils::gdal_rasterize’ by ‘sf::gdal_rasterize’ when loading ‘uavRmp’ 
```
It looks like this is not caused by uavRmp but by one of its dependencies; I couldn't find out which. Selectively importing from them instead of importing most packages completely might resolve this.

**Comment by gisma** [comment]
Thanks for reporting this. I will check it out.

**Comment by gisma** [comment]
Think this works now. I will update the CRAN package during the next weeks.
